-- MySQL Script generated by MySQL Workbench
-- Fri Jul  3 13:07:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbGestionOcupacion
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `dbgestionocupacion` ;

-- -----------------------------------------------------
-- Schema dbGestionOcupacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbgestionocupacion` DEFAULT CHARACTER SET utf8 ;
USE `dbgestionocupacion` ;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`client` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`client` (
  `cli_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cli_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`cli_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.client: ~0 rows (approximately)
/*!40000 ALTER TABLE `client` DISABLE KEYS */;
/*!40000 ALTER TABLE `client` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`user` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`user` (
  `usr_id` INT(11) NOT NULL AUTO_INCREMENT,
  `usr_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `usr_email` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `usr_ci` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `usr_id_trello` INT(11) NULL DEFAULT NULL,
  `usr_id_clockify` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`usr_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.user: ~0 rows (approximately)
/*!40000 ALTER TABLE `user` DISABLE KEYS */;
/*!40000 ALTER TABLE `user` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`request` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`request` (
  `req_id` INT(11) NOT NULL AUTO_INCREMENT,
  `board_id` VARCHAR(50) NULL DEFAULT NULL,
  `project_id` VARCHAR(50) NULL DEFAULT NULL,
  `task_id` VARCHAR(50) NULL DEFAULT NULL,
  `req_ms_project` TEXT NULL DEFAULT NULL,
  `cli_id` INT(11) NULL DEFAULT NULL,
  `coa_id` INT(11) NULL DEFAULT NULL,
  `req_title` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_description` VARCHAR(1024) NULL DEFAULT NULL,
  `req_responsable` VARCHAR(45) NULL DEFAULT NULL,
  `req_order_priority` INT(11) NULL DEFAULT NULL,
  `req_date` DATE NULL DEFAULT NULL,
  `req_init_date` DATE NULL DEFAULT '9999-12-31',
  `req_final_date` DATE NULL DEFAULT '9999-12-31',
  `req_real_final_date` DATE NULL DEFAULT NULL,
  `sta_id` VARCHAR(45) NULL DEFAULT NULL,
  `req_advance_ptge` FLOAT NULL DEFAULT NULL,
  `req_deviations_ptge` FLOAT NULL DEFAULT NULL,
  `req_client_completed_deliverables` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_client_pending_activities` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_client_comments` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_intelix_completed_deliverables` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_intelix_pending_activities` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_intelix_comments` VARCHAR(1024) NULL DEFAULT NULL,
  `req_last_update_date` DATE NULL DEFAULT NULL,
  `rty_id` INT(11) NULL DEFAULT NULL,
  `tea_id` INT(11) NULL DEFAULT NULL,
  `req_comitee` INT(11) NULL DEFAULT NULL,
  `req_comitee_points_discuss` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `req_day_desv` INT(11) NULL DEFAULT NULL,
  `req_cargar` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT 'true',
  PRIMARY KEY (`req_id`),
  INDEX `cli_id_idx` (`cli_id` ASC) ,
  INDEX `coa_id` (`coa_id` ASC) ,
  INDEX `rty_id` (`rty_id` ASC) ,
  INDEX `tea_id` (`tea_id` ASC) ,
  CONSTRAINT `client_id`
    FOREIGN KEY (`cli_id`)
    REFERENCES `dbgestionocupacion`.`client` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=52 DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.request: ~8 rows (approximately)
/*!40000 ALTER TABLE `request` DISABLE KEYS */;
INSERT INTO `request` (`req_id`, `board_id`, `project_id`, `task_id`, `req_ms_project`, `cli_id`, `coa_id`, `req_title`, `req_description`, `req_responsable`, `req_order_priority`, `req_date`, `req_init_date`, `req_final_date`, `req_real_final_date`, `sta_id`, `req_advance_ptge`, `req_deviations_ptge`, `req_client_completed_deliverables`, `req_client_pending_activities`, `req_client_comments`, `req_intelix_completed_deliverables`, `req_intelix_pending_activities`, `req_intelix_comments`, `req_last_update_date`, `rty_id`, `tea_id`, `req_comitee`, `req_comitee_points_discuss`, `req_day_desv`, `req_cargar`) VALUES
	(40, '5ee2fe80dd1a4b0ca12b8514', NULL, NULL, 'LOG-MA15-Modelo de Existencia y Disponibilidad.mpp', NULL, NULL, 'prueba 13', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(45, '5ecc545f367f7d139208c139', NULL, NULL, NULL, NULL, NULL, 'Centro de Desarrollo - Productos Intelix Capítulo ABX', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(46, '5ee2f4d36ec4910464b7e906', NULL, NULL, NULL, NULL, NULL, 'preuba12', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(47, '5ed18e8039bdeb21ec923c5e', NULL, NULL, NULL, NULL, NULL, 'Modificaciones de la página Web de Beconsult', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(48, '5edb080749b93c4eb29534ea', NULL, NULL, NULL, NULL, NULL, 'Prueba', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(49, '5ee3b950f3ce406448212735', NULL, NULL, 'LOG-MA15-Modelo de Existencia y Disponibilidad.mpp', NULL, NULL, 'prueba 14', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(50, '5ef232463d057744796935ce', NULL, NULL, 'LOG-MA15-Modelo de Existencia y Disponibilidad.mpp', NULL, NULL, 'prueba 15', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'false'),
	(51, '5ef2372d1d400065129eabd3', NULL, NULL, 'LOG-MA15-Modelo de Existencia y Disponibilidad.mpp', NULL, NULL, 'Prueba 16', NULL, NULL, NULL, NULL, '9999-12-31', '9999-12-31', NULL, 'open', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'true');
/*!40000 ALTER TABLE `request` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`booking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`booking` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`booking` (
  `boo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cli_id` INT(11) NOT NULL,
  `req_id` INT(11) NOT NULL,
  `usr_id` INT(11) NOT NULL,
  `boo_duration` INT(20) NULL DEFAULT NULL,
  `boo_start_date` DATE NOT NULL,
  `boo_end_date` DATE NOT NULL,
  `boo_percentage` FLOAT NOT NULL,
  PRIMARY KEY (`boo_id`),
  INDEX `cli_id` (`cli_id` ASC) ,
  INDEX `usr_id` (`usr_id` ASC) ,
  INDEX `req_id` (`req_id` ASC) ,
  CONSTRAINT `cli_id`
    FOREIGN KEY (`cli_id`)
    REFERENCES `dbgestionocupacion`.`client` (`cli_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usr_id`
    FOREIGN KEY (`usr_id`)
    REFERENCES `dbgestionocupacion`.`user` (`usr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `req_id`
    FOREIGN KEY (`req_id`)
    REFERENCES `dbgestionocupacion`.`request` (`req_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.booking: ~0 rows (approximately)
/*!40000 ALTER TABLE `booking` DISABLE KEYS */;
/*!40000 ALTER TABLE `booking` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`database_reg`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`database_reg` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`database_reg` (
  `reg_id` INT(11) NOT NULL AUTO_INCREMENT,
  `reg_update_time` DATETIME NOT NULL,
  PRIMARY KEY (`reg_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.database_reg: ~0 rows (approximately)
/*!40000 ALTER TABLE `database_reg` DISABLE KEYS */;
/*!40000 ALTER TABLE `database_reg` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`clockify_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`clockify_task` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`clockify_task` (
  `clo_id` INT NOT NULL AUTO_INCREMENT,
  `clo_task_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `clo_description` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `clo_date` DATETIME NULL DEFAULT '9999-12-31 00:00:00',
  `clo_time` TIME NULL DEFAULT NULL,
  `clo_poject_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`clo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbGestionOcupacion.clockify_task: ~0 rows (approximately)
/*!40000 ALTER TABLE `clockify_task` DISABLE KEYS */;
/*!40000 ALTER TABLE `clockify_task` ENABLE KEYS */;

-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`activities` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`activities` (
  `act_id` INT(11) NOT NULL AUTO_INCREMENT,
  `req_id` INT(11) NULL DEFAULT NULL,
  `act_trello_name` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `act_description_trello` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `act_card_id` VARCHAR(50) NULL DEFAULT NULL,
  `act_init_date` DATETIME NULL DEFAULT '9999-12-31 00:00:00',
  `act_init_real_date` DATETIME NULL DEFAULT NULL,
  `act_end_date` DATETIME NULL DEFAULT '9999-12-31 00:00:00',
  `act_real_end_date` DATETIME NULL DEFAULT NULL,
  `act_estimated_hours` FLOAT NULL DEFAULT NULL,
  `act_desv_percentage` INT(11) NULL DEFAULT NULL,
  `act_day_desv` INT(11) NULL DEFAULT NULL,
  `act_id_parent` INT(11) NULL DEFAULT NULL,
  `act_id_parent2` INT(11) NULL DEFAULT NULL,
  `act_id_prelacion` INT(11) NULL DEFAULT NULL,
  `act_id_project_task` INT(11) NULL DEFAULT NULL,
  `act_id_user_trello` VARCHAR(50) NULL DEFAULT NULL,
  `act_time_loaded` FLOAT NULL DEFAULT NULL,
  `act_status` VARCHAR(10) NOT NULL DEFAULT 'Active',
  `act_porcent` INT(11) NOT NULL DEFAULT '0',
  `act_title` VARCHAR(50) NOT NULL,
  `act_mail` VARCHAR(50) NULL DEFAULT NULL,
  `act_trello_user` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `req_id_idx` (`req_id` ASC) ,
  CONSTRAINT `request_id`
    FOREIGN KEY (`req_id`)
    REFERENCES `dbgestionocupacion`.`request` (`req_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB AUTO_INCREMENT=793 DEFAULT CHARACTER SET = utf8;

-- Dumping data for table dbgestionocupacion.activities: ~24 rows (approximately)
/*!40000 ALTER TABLE `activities` DISABLE KEYS */;
INSERT INTO `activities` (`act_id`, `req_id`, `act_trello_name`, `act_description_trello`, `act_card_id`, `act_init_date`, `act_init_real_date`, `act_end_date`, `act_real_end_date`, `act_estimated_hours`, `act_desv_percentage`, `act_day_desv`, `act_id_parent`, `act_id_parent2`, `act_id_prelacion`, `act_id_project_task`, `act_id_user_trello`, `act_time_loaded`, `act_status`, `act_porcent`, `act_title`, `act_mail`, `act_trello_user`) VALUES
	(769, 51, 'LOG-MA15-Modelo de Existencia y Disponibilidad', NULL, NULL, '2020-06-01 08:00:00', '2020-06-23 13:31:52', '2020-06-26 12:00:00', '2020-06-23 13:32:40', 240, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(770, 51, 'Inicio solicitud', NULL, '5ef23a540615c21ba2144ef2', '2020-06-01 08:00:00', '2020-06-23 13:32:04', '2020-06-05 17:00:00', '2020-06-23 13:32:55', 40, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 20, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(771, 51, 'Existencia Propia y Proveedor', NULL, NULL, '2020-06-08 08:00:00', '2020-06-23 13:32:03', '2020-06-12 12:00:00', '2020-06-23 13:32:54', 68, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(772, 51, 'Implementación de Ajustes de entrada y salida proveedor', NULL, '5ef23a55acc9fc1a27bc0285', '2020-06-08 08:00:00', '2020-06-23 13:32:02', '2020-06-10 17:00:00', '2020-06-23 13:32:53', 36, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(773, 51, 'Creación de nuevos tipos de ajuste', NULL, '5ef23a5469cca12d32b109a9', '2020-06-08 08:00:00', '2020-06-23 13:32:01', '2020-06-08 17:00:00', '2020-06-23 13:32:51', 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(774, 51, 'Validación y completación para los nuevos tipos de ajuste', NULL, '5ef23a56612f766b929b0665', '2020-06-09 08:00:00', '2020-06-23 13:32:00', '2020-06-10 17:00:00', '2020-06-23 13:32:50', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(775, 51, 'Modificación en réplica de Ajuste para llevar data a LEGACY', NULL, '5ef23a547b87cf7847a4f89a', '2020-06-08 08:00:00', '2020-06-23 13:32:00', '2020-06-09 12:00:00', '2020-06-23 13:32:46', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 10, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(776, 51, 'Implementación de ventas propias y proveedor', NULL, NULL, '2020-06-09 13:00:00', '2020-06-23 13:31:59', '2020-06-10 17:00:00', '2020-06-23 13:32:45', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(777, 51, 'Ventas propias', NULL, '5ef23a55f4009a11ed9f2a7c', '2020-06-09 13:00:00', '2020-06-23 13:31:58', '2020-06-10 10:00:00', '2020-06-23 13:32:44', 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(778, 51, 'Ventas proveedor', NULL, '5ef23a54e2db703aeb851f2c', '2020-06-10 10:00:00', '2020-06-23 13:31:55', '2020-06-10 17:00:00', '2020-06-23 13:32:43', 6, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(779, 51, 'Implementación de Ajustes de entrada y salida proveedor', NULL, '5ef23a55acc9fc1a27bc0285', '2020-06-11 08:00:00', '2020-06-23 13:31:54', '2020-06-11 17:00:00', '2020-06-23 13:32:42', 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 60, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(780, 51, 'Implementación de réplica que calcule y almacene las unidades necesarias para la Existencia propia y proveedor en la nueva tabla', NULL, '5ef23a566bf8355b8327db66', '2020-06-11 08:00:00', '2020-06-23 13:31:53', '2020-06-12 12:00:00', '2020-06-23 13:32:41', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, 'Active', 0, 'false', '', 'angel_narvaez'),
	(781, 51, 'Disponibilidad Propia', NULL, NULL, '2020-06-12 08:00:00', '2020-06-23 13:32:09', '2020-06-18 12:00:00', '2020-06-23 13:32:28', 64, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(782, 51, 'Implementación de Fórmula de Existencia propia', NULL, '5ef23a54d3290218c99bf26b', '2020-06-12 08:00:00', '2020-06-23 13:31:51', '2020-06-15 17:00:00', '2020-06-23 13:32:40', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(783, 51, 'Implementación de Fórmula de Mercancia en cuarentena propia', NULL, '5ef23a56288d127267f37c72', '2020-06-12 13:00:00', '2020-06-23 13:31:50', '2020-06-16 12:00:00', '2020-06-23 13:32:39', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(784, 51, 'Implementación de Fórmula de Mercancia en cuarentena propia', NULL, '5ef23a56288d127267f37c72', '2020-06-16 08:00:00', '2020-06-23 13:31:49', '2020-06-17 17:00:00', '2020-06-23 13:32:38', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(785, 51, 'Implementación de Función de Disponibilidad Propia', NULL, '5ef23a555595098768ba4291', '2020-06-16 13:00:00', '2020-06-23 13:31:48', '2020-06-18 12:00:00', '2020-06-23 13:32:37', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(786, 51, 'Disponibilidad Proveedor', NULL, NULL, '2020-06-18 08:00:00', '2020-06-23 13:31:47', '2020-06-25 12:00:00', '2020-06-23 13:32:36', 60, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(787, 51, 'Implementación de Fórmula de Existencia proveedor2', NULL, '5ef23a55ced50634766dfe6d', '2020-06-18 08:00:00', '2020-06-23 13:31:46', '2020-06-19 12:00:00', '2020-06-23 13:32:35', 12, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(788, 51, 'Implementación de Fórmula de Mercancia en cuarentena proveedor', NULL, '5ef23a55a6bbcb81aec3b1c2', '2020-06-18 13:00:00', '2020-06-23 13:31:45', '2020-06-22 12:00:00', '2020-06-23 13:32:35', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 10, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(789, 51, 'Implementación de Fórmula de Ventas proveedor en tránsito', NULL, '5ef23a54781fbd0cf4342eb9', '2020-06-19 13:00:00', '2020-06-23 13:31:43', '2020-06-23 12:00:00', '2020-06-23 13:32:34', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 50, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(790, 51, 'Implementación de Función de Disponibilidad Proveedor', NULL, '5ef23a56d1755a1b51101195', '2020-06-22 13:00:00', '2020-06-23 13:31:41', '2020-06-25 12:00:00', '2020-06-23 13:32:32', 16, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 51, 'false', 'mlomeli@intelix.biz', 'angel_narvaez'),
	(791, 51, 'Disponibilidad Total', NULL, NULL, '2020-06-25 13:00:00', '2020-06-23 13:32:07', '2020-06-26 12:00:00', '2020-06-23 13:32:31', 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'true', '', ''),
	(792, 51, 'Implementación de Función de Disponibilidad Total', NULL, '5ef23a550f31c282d4f259a4', '2020-06-25 13:00:00', '2020-06-23 13:32:09', '2020-06-26 12:00:00', '2020-06-23 13:32:30', 8, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 'Active', 0, 'false', 'mlomeli@intelix.biz', 'angel_narvaez');
/*!40000 ALTER TABLE `activities` ENABLE KEYS */;



-- -----------------------------------------------------
-- Table `dbgestionocupacion`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dbgestionocupacion`.`tickets` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`tickets` (
  `tic_id` INT NOT NULL AUTO_INCREMENT,
  `tic_title` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_description`MEDIUMTEXT CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_branch` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_subsidiary` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_deparment` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_usr_ci` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_category` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_priority` VARCHAR(15) NULL DEFAULT NULL,
  `tic_assigned_to` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `tic_date` DATE NULL DEFAULT NULL,
  `tic_last_update_date` DATE NULL DEFAULT NULL,
  `tic_sol_date` DATE NULL DEFAULT NULL,
  `tic_closing_date` DATE NULL DEFAULT NULL,
  `tic_clockify_time` TIME NULL DEFAULT NULL,
  `tic_sla` INT(11) NULL DEFAULT NULL,
  `tic_card_init` VARCHAR(45) CHARACTER SET 'utf8' NULL DEFAULT 'false',
  PRIMARY KEY (`tic_id`))
ENGINE = InnoDB;

DROP TABLE IF EXISTS `dbgestionocupacion`.`ramo` ;

CREATE TABLE IF NOT EXISTS `dbgestionocupacion`.`branch` (
  `ram_id` INT NOT NULL AUTO_INCREMENT,
  `ram_name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL DEFAULT NULL,
  `board_id` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ram_id`))
ENGINE = InnoDB;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
